- MODULE.bazel
- README.md
- helm/helm.bzl
- helm/private/helm_import.bzl
- helm/private/helm_install.bzl
- helm/private/helm_package.bzl
- helm/private/installer/helm_install.bat.template
- helm/private/installer/helm_install.sh.template
- helm/private/packager/packager.go
- helm/private/pusher/helm_push.bat.template
- helm/private/pusher/helm_push.sh.template
- helm/private/reinstaller/helm_reinstall.bat.template
- helm/private/reinstaller/helm_reinstall.sh.template
- helm/providers.bzl
- tests/test_deps.bzl
- tests/with_image_deps/BUILD.bazel
- tests/with_image_deps/values.yaml
This allows for easier upgrades to the `rules_oci` supported releases
> Renamed `oci_image` attributes to `image`

- .bcr/presubmit.yml
Ideally there'd be an integration test within the repo that tests consuming the rules via bzl mod. For now this aims to release something in the short-term.
> Change test directory for bazel-central-repository tests

- MODULE.bazel
- README.md
- WORKSPACE.bazel
- helm/private/helm_package.bzl
- helm/private/json_to_yaml/json_to_yaml.go
- helm/private/packager/packager.go
- tests/with_image_deps/BUILD.bazel
This PR adds an aspect to figure out the repository name of container images. `images` is now a dict where the key is a oci_push target and the value is the replacement string to be found in the values.yaml. All images must be found in the values.yaml.
This also updates packager.go to use idiomatic go and go error handling.
> Add an aspect to figure out the repository name of container images.

- MODULE.bazel
- MODULE.bazel.lock
- helm/private/packager/packager.go
- helm/repositories_transitive.bzl
Use of `exec.Command.Environ` is unnecessary and increased the min supported version of golang. It's use has been removed
> Support older versions of golang

- README.md
- helm/private/helm.bzl
All targets should be able to build. All of the targets that has `manual` tags will only have side-effects if they're run so there's no risk in building them.
Also, the `tags` were all screwed up because `tags` was an argument and it was being extracted from `**kwargs` so it was impossible to pass in additional `tags`.
> Remove manual tags.

- 3rdparty/bazel-lib/BUILD.bazel
- 3rdparty/bazel-lib/README.md
- 3rdparty/bazel-lib/repo_utils.bzl
- MODULE.bazel.lock
- docs/BUILD.bazel
- helm/repositories.bzl
Fixes https://github.com/abrisco/rules_helm/issues/78.
> fix: incorrect host alias symlink on some platforms

- MODULE.bazel.lock
- README.md
- helm/extensions.bzl
- helm/private/versions.bzl
- helm/repositories.bzl
Also bumps the version of Helm to [3.15.0](https://github.com/helm/helm/releases/tag/v3.15.0)
closes https://github.com/abrisco/rules_helm/issues/76
> Update helm artifacts to use `integrity`

- MODULE.bazel.lock
- README.md
- helm/private/helm.bzl
- helm/private/helm_package.bzl
- helm/private/packager/packager.go
- tests/simple/crds/test.crd.yaml
Solves #84.
The implementation follows the flow of the `templates` folder, but considers that `crds` folder is optional.
> Add support for crds in the packaged chart

- .github/workflows/ci.yaml
To account for https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
> Update outdated MacOS CI runner

- MODULE.bazel.lock
- helm/private/helm_package.bzl
- helm/private/packager/packager.go
- tests/with_image_deps/BUILD.bazel
- tests/with_image_deps/values.yaml
I would like to suggest some enhancements regarding `oci_push` image referencing and replacements in chart files. 
Sometimes it's more convenient to see meaningful Docker image tag in k8s specs instead of sha256 (otherwise we didn't add these tags to Docker images). In our case these tags are available from `oci_push` target (along with repository file). So we can try to use them in chart files replacements.
Besides that a lot of existing charts have separated settings for image repository and image tag. 
```
image:
repository: docker.io/busybox
tag: v1.2.3
```
So it would be useful to add separate replacements for these parameters so that people don't need to change structure of theirs charts in order to make them correctly packaged by `rules_helm`. Moreover, there are charts exist that …
> remote_tag can be used as image ref

- MODULE.bazel
This was overlooked in #98 and #105 when rules_oci was marked as dev dependency.
Without this change, depending on this module fails as loading the extension fails as evaluating `test_extensions.bzl` fails when loading `test_deps.bzl` which again tries to load from `@rules_oci` which it can't resolve as it is a dev dependency.
> Mark test dependencies as dev dependencies

- MODULE.bazel
- MODULE.bazel.lock
- README.md
- helm/defs.bzl
- helm/private/helm.bzl
- helm/private/helm_install.bzl
- helm/private/helm_registry.bzl
- helm/private/registrar/helm_registry.bat.template
- helm/private/registrar/helm_registry.sh.template
- version.bzl
This change also renames the `helm_push` rule to `helm_push_images` so that `helm_push_registry` can be renamed to `helm_push`.
> Added `include_images` to `helm_push` rule.

- helm/extensions.bzl
- Rename `helm.options` to `helm.toolchain` and this tag generates a new toolchain
- Handle multiple extension calls correctly
> Improve module extension

- MODULE.bazel
- helm/extensions.bzl
Improvements after #130. This makes sure that there is always exactly one toolchain defined, either in the root module or picking the default one.
> Always generate exactly one toolchain

- helm/private/helm.bzl
- helm/private/helm_registry.bzl
- helm/private/registrar/registrar.go
Closes #140.
To push chart packages to ChartMuseum registries, one needs to run `helm cm-push` instead of the default `helm push`.
The present change simply consists in adding an optional `push_cmd` string argument to the `helm_chart` macro definition and propagate it down to the registrar.
I've verified the change manually by overriding the `rules_helm` repository using the present branch, but didn't find a simple way to test it yet.
> Allow alternative `push` commands

- .bcr/metadata.template.json
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- MODULE.bazel
- helm/private/versions.bzl
Bumped various bzlmod deps and updated ubuntu runner above `ubuntu-20.04` to avoid Github deprecation.
> Update transitive dependencies

- docs/src/index.md
Bzlmod is replacing `WORKSPACE` in Bazel 8 and will be removed from Bazel 9:
https://bazel.build/external/migration#define-root
> Update setup directions for using MODULE.bazel

- helm/private/runner/runner.go
`fmt.Errorf` calls were missing the %w verb, so the actual error wouldn't be logged.
`fmt.Printf` was being used without args, so change to `fmt.Print`
> Fix fmt.Errorf and fmt.Printf calls in runner.go

- .github/workflows/ci.yaml
The `windows-2019` image has been removed (https://github.com/actions/runner-images/issues/12045), so checks are failing.
> Switch to `windows-latest` image

- helm/private/helm_import.bzl
- tests/test_deps.bzl
Download the chart specified by `url`, assuming the URL is a valid chart file name to determine the name and version.
This PR also makes the `url` attribute exclusive with `chart_name`, `repository`, and `version`.
> Update `helm_import_repository` to support only specifying URL

- helm/private/runner/runner.go
This variable is effectively unused since it is only used to print what I assume is debugging data, but is never actually used when invoking `helm`.
> Remove unused `cleanArgs` variable from runner.go

- helm/defs.bzl
- helm/private/helm_template.bzl
- helm/private/templater/BUILD.bazel
- helm/private/templater/templater.go
- tests/no_templates/BUILD.bazel
- tests/simple/BUILD.bazel
I wasn't able to reuse https://github.com/abrisco/rules_helm/blob/main/helm/private/runner/runner.go since that only seems to be useful as a binary target in `bazel run` and not to write an output file instead.
Support for passing values files to `helm template` will also be added.
> Add `helm_template` rule to write the output from `helm template` to a file

- docs/BUILD.bazel
- helm/private/helm_import_authn.bzl
Support pulling charts from private OCI repos using Docker Credential Helpers to acquire credentials.
Heavily based on https://github.com/bazel-contrib/rules_oci/blob/main/oci/private/authn.bzl.
I have manually tested this with a GCP Artifact Registry repository, but can't commit those changes.
Fixes #125
> Add support for pulling charts from private OCI repos
