abrisco/rules_helm

tests/private/package_regex_tester/BUILD.bazel, tests/private/package_regex_tester/package_regex_tester.go, tests/test_defs.bzl, tests/with_image_deps/BUILD.bazel, tests/with_image_deps/values.yaml
Nothing actually ensures image stubs are resolved when a package is created. This change adds regression testing for that.
=> Added a test rule to help ensure images are correctly resolved in packages

.bcr/metadata.template.json, .bcr/presubmit.yml, .bcr/source.template.json, BUILD.bazel, MODULE.bazel, tests/bzl_version/BUILD.bazel, tests/bzl_version/bzl_version_test.go
https://github.com/bazelbuild/bazel-central-registry
=> Added publishing to bazel-central-registry

README.md, helm/private/versions.bzl
https://github.com/helm/helm/releases/tag/v3.13.3
=> Added Helm 3.13.3

.bcr/presubmit.yml
Relates to https://github.com/abrisco/rules_helm/issues/1
=> Drop windows builds as they're unsupported currently

.bcr/presubmit.yml
Relates to https://github.com/abrisco/rules_helm/issues/38
=> Add mandatory module path

.bazelignore, BUILD.bazel, README.md, helm/defs.bzl, helm/helm.bzl, helm/private/BUILD.bazel, helm/private/helm_install.bzl, helm/private/helm_registry.bzl, helm/private/registrar/BUILD.bazel, helm/private/registrar/helm_registry.bat.template, helm/private/registrar/helm_registry.sh.template, helm/private/reinstaller/helm_reinstall.sh.template
- Add the ability to push a helm package to an oci registry
relates to https://github.com/abrisco/rules_helm/pull/30 (special thanks to @iDiogenes)
=> Add helm_push_registry

README.md, helm/helm.bzl, helm/private/helm_package.bzl
Also cleans up the chart / chart_json error messages.
=> Allow overriding chart, chart_json, values, and values_json in helm_chart

.bazelrc, .bcr/presubmit.yml, .github/workflows/ci.yaml, helm/private/linter/linter.go, helm/private/packager/packager.go, tests/bzl_version/bzl_version_test.go, tests/version_stamp/version_stamp_unit_test.bzl, tests/with_image_deps/BUILD.bazel, tools/workspace_status.bat
closes https://github.com/abrisco/rules_helm/issues/1
=> Enable windows in CI

helm/private/packager/packager.go
Having a kube config installed on a host with bad permissions would cause `HelmPackage` actions to fail with the following
```
ERROR: /Users/user/Code/rules_helm/tests/version_stamp/BUILD.bazel:3:25: Creating Helm Package for @@//tests/version_stamp:version_stamp.stamp failed: (Exit 1): packager failed: error executing HelmPackage command (from target //tests/version_stamp:version_stamp.stamp)
(cd /private/var/tmp/_bazel_user/5f6cb807741f123860937f76a6878615/sandbox/darwin-sandbox/148/execroot/_main && \
exec env - \
bazel-out/darwin_arm64-opt-exec-ST-13d3ddad9198/bin/helm/private/packager/packager_/packager -output bazel-out/darwin_arm64-fastbuild/bin/tests/version_stamp/version_stamp.stamp.tgz -metadata_output bazel-out/darwin_arm64-fastbuild/bin/tests/version_stamp/version_stamp.stamp.m …
```
=> Sanitize KUBECONFIG environment variable when creating packages

helm/private/linter/linter.go
When running without a sandbox, lint actions can occasionally stomp on each other due to the common `.rules_helm_lint_dir` directory. This directory should be replaced with one unique to each action.
=> Ensure HelmLint actions run in their own directories

.bcr/presubmit.yml
Relates to https://github.com/bazelbuild/bazel-central-registry/pull/1396#issuecomment-1927347464
=> Added Bazel version matrix to bzlmod build plan

helm/private/packager/packager.go, tests/version_stamp/Chart.yaml, tests/version_stamp/version_stamp_unit_test.bzl
Implements https://github.com/abrisco/rules_helm/pull/67
=> Add support for `+` in package versions

LICENSE-MIT
closes https://github.com/abrisco/rules_helm/issues/88
=> Add MIT License

MODULE.bazel, MODULE.bazel.lock, tests/test_deps.bzl, tests/with_chart_deps/BUILD.bazel, tests/with_chart_deps/Chart.yaml, tests/with_chart_deps/with_chart_deps_test.go
closes https://github.com/abrisco/rules_helm/issues/91
=> Improved test for helm chart deps

MODULE.bazel.lock, README.md, helm/private/versions.bzl
https://github.com/helm/helm/releases/tag/v3.16.1
=> Updated default Helm version to 3.16.1

MODULE.bazel, MODULE.bazel.lock, helm/extensions.bzl, tests/test_extensions.bzl
closes https://github.com/abrisco/rules_helm/issues/104
=> Separate out test dependencies from the core bzlmod extensions

MODULE.bazel.lock, README.md, helm/defs.bzl, helm/extensions.bzl, helm/private/BUILD.bazel, helm/private/current_toolchain.bzl, helm/private/helm.bzl, helm/private/helm_cmd/BUILD.bazel, helm/private/helm_cmd/helm_cmd.go, helm/private/helm_lint.bzl, helm/private/helm_package.bzl, helm/private/helm_registry.bzl, helm/private/helm_toolchain.bzl, helm/private/linter/BUILD.bazel, helm/private/linter/linter.go, helm/private/packager/BUILD.bazel, helm/private/packager/packager.go, helm/private/plugin/BUILD.bazel, helm/private/plugin/plugin_builder.go, helm/private/registrar/BUILD.bazel, helm/private/registrar/registrar.go, helm/repositories.bzl, helm/toolchain.bzl, tests/test_deps.bzl, tests/toolchain_with_plugins/BUILD.bazel
https://helm.sh/docs/topics/plugins/
=> Added support for helm plugins

MODULE.bazel, MODULE.bazel.lock, helm/private/helm_cmd/helm_cmd.go, version.bzl
=> Release 0.9.1

MODULE.bazel, helm/private/helm_registry.bzl, version.bzl
=> Release 0.9.2

.bcr/presubmit.yml
Fixes the issues observed in https://github.com/bazelbuild/bazel-central-registry/pull/3724
=> Fix bazel-central-registry CI

.bcr/metadata.template.json, .bcr/presubmit.yml, .bcr/source.template.json
Fixes https://github.com/bazelbuild/bazel-central-registry/pull/4351#issuecomment-2814158737
=> Fixed releases

.github/workflows/ci.yaml
https://github.com/actions/runner-images/issues/12045
=> Updated CI workers

helm/private/versions.bzl
https://github.com/helm/helm/releases/tag/v3.18.4
=> Add new Helm versions to `versions.bzl` and switch default version to 3.18.4
